version: '3.9'
services:
  backend:
    build: ./backend
    volumes:
      - ./config.json:/app/config.json   # редактируемый конфиг
      - ./logs:/app/logs                # куда писать found_tenders.json и логи
    ports: [ "8000:8000" ]

  frontend:
    build: ./frontend
    ports: [ "8080:80" ]
    depends_on: [ backend ]
