services:
  api:
    build: ./backend
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    env_file: .env
    depends_on: [redis, db]

  worker:
    build: ./backend
    command: celery -A tasks.celery worker --loglevel=info
    env_file: .env
    depends_on: [redis, db]

  beat:
    build: ./backend
    command: celery -A tasks.celery beat --loglevel=info
    env_file: .env
    depends_on: [redis, db]

  redis:
    image: redis:7
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tender
      POSTGRES_USER: tender
      POSTGRES_PASSWORD: tender
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports: ["80:80"]
    depends_on: [api, admin]

  admin:        # статика Flutter
    build: ./frontend
    depends_on: []