version: '3.9'          # можно и вовсе опустить – в Compose Spec он устарел
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./config.json:/app/config.json
      - ./logs:/app/logs
    ports: ["8000:8000"]

    # ───────────────────────────────────────────────
    deploy:
      resources:
        limits:
          memory: 2g        # жёсткая граница
        reservations:
          cpus: '0.80'     # гарантировано пол-ядра (optional)

  frontend:
    build: ./frontend
    ports: ["8080:80"]
    depends_on: [ backend ]
