version: '3.9'
services:
  backend:
    build:
      context: .                 #  ←  теперь в контексте и backend/, и config.json
      args:
        - PASSWORD_ADMIN
      dockerfile: backend/Dockerfile
    environment:
      - PASSWORD_ADMIN=${PASSWORD_ADMIN}
    volumes:
      - ./config.json:/app/config.json     # остаётся, чтобы правки на хосте сразу
      - ./logs:/app/logs
    ports: ["8000:8000"]

  frontend:
    build: ./frontend
    ports: [ "8080:80" ]
    depends_on: [ backend ]
