version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./config.json:/app/config.json           # ваши настройки
      - ./logs:/app/logs                         # логи и JSON-вывод парсера
      - tender_parser_repo:/opt/parser           # код + модели Stanza
    environment:
      - CRON_EXPR=0 2 * * *                      # плановый запуск (пример)
      - TZ=Asia/Tbilisi
    ports: ["8000:8000"]

  frontend:
    build: ./frontend
    depends_on: [ backend ]
    ports: ["8080:80"]

volumes:
  tender_parser_repo: